### ISSUE TITLE
[Request] Dark theme

### ISSUE THREAD

**Issue by ivanddm** [0xk175un3/susuwatari#2]
Hi there,

Thanks a lot for this theme. I really like it compared to other monochromatic white themes out there, it has the right amount of bolded syntax, and the normal font color is just the right amount of black.

I'm using this theme in the day. Any chance that you will publish a black monochromatic theme to use it during the night 🤓?

**Comment by 0xk175un3** [comment]
Hello!

Thanks for using my theme! 
And yes there are plans to create a black monochromic variant of this theme later.
I don't know when, but it will be for sure :)

**Comment by ivanddm** [comment]
That sounds great! Thanks in advance.
